# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3.8"

networks:
  am-d-model-network:
    name: am-d-model-network

services:
  site:
    build: .
    networks:
      - am-d-model-network
    expose:
      - "3000"
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=local"

  caddy:
    image: docker.io/library/caddy:latest
    depends_on:
        - site
    networks:
      - am-d-model-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=registry"
