version: "3.8"

networks:
  am-d-model-network:
    name: am-d-model-network

services:
  site:
    build: .
    networks:
      - am-d-model-network
    expose:
      - "3000"
    restart: unless-stopped

  caddy:
    image: docker.io/library/caddy:latest
    depends_on:
        - site
    networks:
      - am-d-model-network
    ports:
      - "8080:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy:/etc/caddy
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=registry"

volumes:
  caddy_data:
  caddy_config:
