version: "3.8"

networks:
  am-d-model-network:
    name: am-d-model-network

services:
  site:
    build: .
    networks:
      - am-d-model-network
    expose:
      - "3000"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    depends_on:
        - site
    networks:
      - am-d-model-network
    ports:
      - "8080:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: >
      sh -c "wget -O /etc/caddy/Caddyfile https://raw.githubusercontent.com/Cian-H/am-d-model.eu/refs/heads/main/conf/Caddyfile &&
      caddy run --config /etc/caddy/Caddyfile"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
