# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  site:
    build: .
    networks:
      - am-d-model-network
    expose:
      - "3000"
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=local"
    volumes:
      - ./logs:/logs

  caddy:
    image: docker.io/library/caddy:latest
    depends_on:
        - site
    networks:
      - am-d-model-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ./caddy:/etc/caddy
    restart: unless-stopped
    labels:
      - "io.containers.autoupdate=registry"

  repo-placeholder:
    image: docker.io/nginx:alpine
    networks:
      - am-d-model-network
    expose:
      - "80"
    volumes:
      - ./repo:/usr/share/nginx/html

networks:
  am-d-model-network:
    name: am-d-model-network


volumes:
  caddy_data:
